# Generated by Django 4.1.1 on 2022-10-01 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dep',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('isWorking', models.BooleanField(default=True)),
                ('date_change', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=40)),
                ('firstname', models.CharField(max_length=40)),
                ('patronymic', models.CharField(blank=True, max_length=40)),
                ('date_change', models.DateTimeField(auto_now_add=True)),
                ('code_dep', models.ForeignKey(default='0', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.dep')),
            ],
        ),
        migrations.AddField(
            model_name='dep',
            name='id_head',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.employee'),
        ),
    ]
