# Generated by Django 4.1.1 on 2022-10-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dep_id_head_alter_employee_code_dep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dep',
            name='id_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='code_dep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dep'),
        ),
    ]
