# Generated by Django 4.1.1 on 2022-10-02 13:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_dep_id_head_alter_employee_code_dep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='code_dep',
        ),
        migrations.AddField(
            model_name='dep',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 2, 13, 31, 58, 372766, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='date_transfer',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='id_dep_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_dep_new', to='api.dep'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_dep_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_dep_old', to='api.dep'),
        ),
        migrations.AlterField(
            model_name='dep',
            name='date_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_change',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
