# Generated by Django 4.1.1 on 2022-10-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_employee_code_dep_dep_date_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_transfer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
