# Generated by Django 4.1.1 on 2022-10-03 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_employee_date_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_dep_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dep_new', to='api.dep'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_dep_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dep_old', to='api.dep'),
        ),
    ]
