# Generated by Django 4.1.1 on 2022-10-09 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_employee_id_dep_new_alter_employee_id_dep_old'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dep',
            options={'verbose_name': 'dep', 'verbose_name_plural': 'deps'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
        migrations.AlterField(
            model_name='dep',
            name='id',
            field=models.CharField(db_column='id', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='dep',
            old_name='id',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='dep',
            old_name='isWorking',
            new_name='is_working',
        ),
        migrations.RemoveField(
            model_name='dep',
            name='id_head',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_transfer',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_dep_new',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id_dep_old',
        ),
        migrations.AddField(
            model_name='dep',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_dep', to='api.employee'),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transfer', models.DateTimeField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_change', models.DateTimeField(auto_now=True)),
                ('dep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='api.dep')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='api.employee')),
            ],
            options={
                'verbose_name': 'transfer',
                'verbose_name_plural': 'transfers',
            },
        ),
    ]
